app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login_view"),
    path("logout", views.logout_view, name="logout_view"),
    path("password-reset", views.password_reset_view, name="password-reset"),
    path("send-invitation", views.send_invitation, name="send-invitation"),
    path("signup", views.signup_code, name="signup-code"),
    path("signup/<str:value>", views.signup, name="signup"),
    path("change-profile-settings", views.change_profile_settings, name="change-profile-settings"),
    path("change-password", views.change_password, name="change-password"),
    path("backup", views.backup, name="backup"),
    path("restore", views.restore, name="restore"),
    path("upload-profile-pic", views.upload_profile_pic, name="upload-profile-pic"),
    path("delete", views.delete, name="delete"),
    path("create-chat", views.create_chat, name="create-chat"),
    path("chat/<str:uuid>/", views.chat, name="chat"),
    path("chat/<str:uuid>/update-chat-members", views.update_chat_members, name="update-chat-members"),
    path("chat/<str:uuid>/edit-chat", views.edit_chat, name="edit-chat"),
    path("chat/<str:uuid>/delete-chat", views.delete_chat, name="delete-chat"),
    path("chat/<str:uuid>/empty-chat", views.empty_chat, name="empty-chat"),
    path("chat/<str:uuid>/leave-chat", views.leave_chat, name="leave-chat"),
    path("chat/<str:uuid>/request-mediation", views.request_mediation, name="request-mediation"),
    path("chat/<str:uuid>/generate-user-answer", views.generate_user_answer, name="generate-user-answer"),
    path("conflict-info", views.conflict_info, name="conflict-info"),
]

mrfusion/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("app.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user_profile")
    profile_pic = models.ImageField(upload_to="media/profile_pics/", default="default.jpg")
    is_party = models.BooleanField(default=True)
    initial_interview_concluded = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    
    def username(self):
        return self.user.username
    
    def email(self):
        return self.user.email
    
    def first_name(self):
        return self.user.first_name
    
    def last_name(self):
        return self.user.last_name
    

class ConflictInfo(models.Model):
    #subject = models.CharField(max_length=255, db_index = True)
    description = models.TextField(blank=True, null=True, default="")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="created_by")
    created_at = models.DateTimeField(auto_now_add=True)

class Question(models.Model):
    question = models.TextField(blank=True, null=True, default="")
    answer = models.TextField(blank=True, null=True, default="")
    question_for = models.ForeignKey(User, on_delete=models.CASCADE, related_name="question_for")


class InvitationToken(models.Model):
    id = models.AutoField(primary_key=True)
    invitation_from = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=0, related_name="invitations")
    invitation_to = models.CharField(max_length=255)
    message = models.TextField(blank=True, null=True, default="")
    token = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)


class Chat(models.Model):
    uuid = models.CharField(max_length=255, primary_key=True)
    permalink = models.CharField(max_length=255)
    name = models.CharField(max_length=255, db_index = True)
    description = models.TextField(blank=True, null=True, default="")
    members = models.ManyToManyField(User)
    created_at = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="owner")
    is_caucus = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    
class ChatHistory(models.Model):
    id = models.AutoField(primary_key=True)
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    sent_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    is_llm = models.BooleanField(default=False)
    is_relevant = models.BooleanField(default=True)
    message = models.TextField(blank=True, null=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.message


class Context(models.Model):
    id = models.AutoField(primary_key=True)
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    context_type = models.CharField(max_length=255, default="")
    data = models.JSONField()
    created_at = models.DateTimeField(auto_now_add=True)

app/forms.py
from django import forms


class LoginForm(forms.Form):
    #username = forms.EmailField(label="Email", max_length=100, widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Email"}))
    username = forms.CharField(label="Email", max_length=100, widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Email", "autocomplete": "off"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control", "placeholder":"Password"}))


class PasswordResetForm(forms.Form):
    email = forms.EmailField(label="Email", max_length=100, widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Email", "id":"password_reset_form_email_id"}))


class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control", "placeholder":"Current password"}))
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control", "placeholder":"New password"}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control", "placeholder":"Confirm password"}))


class InvitationForm(forms.Form):
    email = forms.EmailField(label="Email", max_length=100, widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Email", "autocomplete": "off", "id":"invitation_form_email_id"}))
    #message = forms.CharField(label="Description", max_length=1000, widget=forms.Textarea(attrs={"class":"form-control", "rows":5, "data-autosize":"true", "style":"min-height: 100px;"}), required=False)

class SignupForm(forms.Form):
    username = forms.CharField(label="Username", max_length=100, widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Username", "autocomplete": "off"}))
    first_name = forms.CharField(label="First name", max_length=100, widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"First Name", "autocomplete": "off"}))
    last_name = forms.CharField(label="Last name", max_length=100, widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Last Name", "autocomplete": "off"}))
    email = forms.EmailField(label="Email", max_length=100, widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Email", "autocomplete": "off", "id":"signup_form_email_id"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control", "placeholder":"Password"}))
    token = forms.CharField(widget = forms.HiddenInput())

class SignupCodeForm(forms.Form):
    username = forms.CharField(label="Username", max_length=100, widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Username", "autocomplete": "off"}))
    first_name = forms.CharField(label="First name", max_length=100, widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"First Name", "autocomplete": "off"}))
    last_name = forms.CharField(label="Last name", max_length=100, widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Last Name", "autocomplete": "off"}))
    email = forms.EmailField(label="Email", max_length=100, widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Email", "autocomplete": "off", "id":"signup_form_email_id"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control", "placeholder":"Password"}))
    code = forms.CharField(label="Code", max_length=100, widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Code", "autocomplete": "off"}))


class ProfileSettingsForm(forms.Form):
    username = forms.CharField(label="Username", max_length=100, widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Username", "autocomplete": "off"}))
    first_name = forms.CharField(label="First name", max_length=100, widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"First Name", "autocomplete": "off"}))
    last_name = forms.CharField(label="Last name", max_length=100, widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Last Name", "autocomplete": "off"}))
    email = forms.EmailField(label="Email", max_length=100, widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Email", "autocomplete": "off", "id":"profile_settings_form_email_id"}))
    is_party = forms.BooleanField(label="Party to conflict", widget=forms.CheckboxInput(attrs={"class":"form-check-input"}), required=False)

class UploadBackupFileForm(forms.Form):
    backup_file = forms.FileField(widget=forms.FileInput(attrs={"class":"form-control"}))


class UploadProfilePicForm(forms.Form):
    file = forms.ImageField()
    #file = forms.FileField()

class ConflictInfoForm(forms.Form):
    #subject = forms.CharField(label="Subject", max_length=100, widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Subject","autocomplete": "off",}))
    attrs={
        "class":"form-control", 
        "rows":5, 
        "data-autosize":"true",
        "autocomplete": "off", 
        "style":"overflow-y: scroll; min-height: 110px;",
        "id":"conflict_info_form_description_id",
        }
    description = forms.CharField(label="Description", max_length=10000, widget=forms.Textarea(attrs=attrs), required=False)


class CreateChatForm(forms.Form):
    name = forms.CharField(label="Name", max_length=100, widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Chat name","autocomplete": "off", "id":"create_chat_form_name_id"}))
    attrs={
        "class":"form-control", 
        "rows":8, 
        "data-autosize":"true",
        "autocomplete": "off", 
        "style":"min-height: 100px;",
        "id":"create_chat_form_description_id",
        }
    description = forms.CharField(label="Description", max_length=1000, required=False, widget=forms.Textarea(attrs=attrs))
    members = forms.MultipleChoiceField(widget  = forms.CheckboxSelectMultiple, required=False)

class EditChatForm(forms.Form):
    name = forms.CharField(label="Name", max_length=100, widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Chat name","autocomplete": "off", "id":"edit_chat_form_name_id"}))
    attrs={
        "class":"form-control", 
        "rows":8, 
        "data-autosize":"true",
        "autocomplete": "off", 
        "style":"min-height: 100px;",
        "id":"edit_chat_form_description_id",
        }
    description = forms.CharField(label="Description", max_length=1000, required=False, widget=forms.Textarea(attrs=attrs))


class UpdateChatMembersForm(forms.Form):
    members = forms.MultipleChoiceField(widget  = forms.CheckboxSelectMultiple, required=False)


class ChatForm(forms.Form):
    attrs = {
        "autocomplete": "off",
        "class":"form-control px-0", 
        "placeholder":"Type your message...",
        "rows":1,
        "data-emoji-input":"",
        "data-autosize":"true"
        }
    chat_message = forms.CharField(label="Chat message", max_length=1000, widget=forms.TextInput(attrs=attrs))
    """
    uploaded_file = forms.FileField(
		required=False,
		widget=forms.ClearableFileInput(attrs={'class': 'form-control'})
	)
    """

app/templates/chat-message.html
{% load static %}
<div id="chat-message" hx-swap-oob="beforeend">
    <!-- Message -->
    <div class="message message-out">
        <a href="#" data-bs-toggle="modal" data-bs-target="#modal-profile" class="avatar avatar-responsive">
            <img class="avatar-img" src="{{user_profile.profile_pic.url}}" alt="{{message.sent_by.first_name}} {{message.sent_by.last_name}}">
        </a>

        <div class="message-inner">
            <div class="message-body">
                <div class="message-content">
                    <div class="message-text">
                        <p>{{message}}</p>
                    </div>
                </div>
            </div>

            <div class="message-footer">
                <span class="extra-small text-muted">{{message.created_at}}</span>
            </div>
        </div>
    </div>
</div>

app/templates/home.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<!-- Chat -->
<main class="main">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
    <div class="container h-100">
        <div class="d-flex flex-column h-100 justify-content-center text-center">
            <p class="text-muted">Select a Chat from the left menu.</p>
        </div>
    </div>
</main>
<!-- Chat -->
{% endblock %}

app/templates/mediator-message.html
{% load static %}
<div id="chat-message" hx-swap-oob="beforeend">
    <!-- Message -->
    <div class="message">
        <a href="#" data-bs-toggle="modal" data-bs-target="#modal-profile" class="avatar avatar-responsive">
            <img class="avatar-img" src="{% static "assets/img/avatars/mr_fusion.jpg" %}" alt="MrFusion">
        </a>

        <div class="message-inner">
            <div class="message-body">
                <div class="message-content">
                    <div class="message-text">
                        <p>{{message}}</p>
                    </div>
                </div>
            </div>

            <div class="message-footer">
                <span class="extra-small text-muted">{{message.created_at}}</span>
            </div>
        </div>
    </div>
</div>

app/templates/modal-profile.html
{% load static %}

<!-- Modal: Profile -->
<div class="modal fade" id="modal-profile" tabindex="-1" aria-labelledby="modal-profile" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-fullscreen-xl-down">
        <div class="modal-content">

            <!-- Modal body -->
            <div class="modal-body py-0">
                <!-- Header -->
                <div class="profile modal-gx-n">
                    <div class="profile-img text-primary rounded-top-xl">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 400 140.74"><defs><style>.cls-2{fill:#fff;opacity:0.1;}</style></defs><g><g><path d="M400,125A1278.49,1278.49,0,0,1,0,125V0H400Z"/><path class="cls-2" d="M361.13,128c.07.83.15,1.65.27,2.46h0Q380.73,128,400,125V87l-1,0a38,38,0,0,0-38,38c0,.86,0,1.71.09,2.55C361.11,127.72,361.12,127.88,361.13,128Z"/><path class="cls-2" d="M12.14,119.53c.07.79.15,1.57.26,2.34v0c.13.84.28,1.66.46,2.48l.07.3c.18.8.39,1.59.62,2.37h0q33.09,4.88,66.36,8,.58-1,1.09-2l.09-.18a36.35,36.35,0,0,0,1.81-4.24l.08-.24q.33-.94.6-1.9l.12-.41a36.26,36.26,0,0,0,.91-4.42c0-.19,0-.37.07-.56q.11-.86.18-1.73c0-.21,0-.42,0-.63,0-.75.08-1.51.08-2.28a36.5,36.5,0,0,0-73,0c0,.83,0,1.64.09,2.45C12.1,119.15,12.12,119.34,12.14,119.53Z"/><circle class="cls-2" cx="94.5" cy="57.5" r="22.5"/><path class="cls-2" d="M276,0a43,43,0,0,0,43,43A43,43,0,0,0,362,0Z"/></g></g></svg>

                        <div class="position-absolute top-0 start-0 py-6 px-5">
                            <button type="button" class="btn-close btn-close-white btn-close-arrow opacity-100" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                    </div>

                    <div class="profile-body">
                        <div class="avatar avatar-xl">
                            <span class="avatar-text bg-primary">
                                {% if user_profile.profile_pic.url %}
                                    <img class="avatar-img" src="{{user_profile.profile_pic.url}}" alt="{{user.first_name}} {{user.last_name}}">
                                {% else %}
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-image"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><circle cx="8.5" cy="8.5" r="1.5"></circle><polyline points="21 15 16 10 5 21"></polyline></svg>
                                {% endif %}
                            </span>
                            <div class="badge badge-lg badge-circle bg-primary border-outline position-absolute bottom-0 end-0">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>
                            </div>

                            <form method="post" enctype="multipart/form-data" name="upload_profile_pic_form" action="{% url 'upload-profile-pic' %}">
                                {% csrf_token %}
                                <input class="d-none" type="file" name="file" id="id_file" onchange="document.upload_profile_pic_form.submit()">
                                <label class="stretched-label mb-0" for="id_file"></label>
                            </form>
                        </div>

                        <h4 class="mb-1">{{user.first_name}} {{user.last_name}}</h4>
                    </div>
                </div>
                <!-- Header -->

                <hr class="hr-bold modal-gx-n my-0">

                <!-- List -->
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <div class="row align-items-center gx-6">
                            <div class="col">
                                <h5>E-mail</h5>
                                <p>{{user.email}}</p>
                            </div>

                            <div class="col-auto">
                                <div class="btn btn-sm btn-icon btn-dark">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-mail"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
                <!-- List  -->
                <hr class="hr-bold modal-gx-n my-0">
                <!-- List -->
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <a href="/logout" class="text-danger">Logout</a>
                    </li>
                </ul>
                <!-- List -->
            </div>
            <!-- Modal body -->

        </div>
    </div>
</div>

app/templates/sidebar.html
{% load static %}

<!-- Sidebar -->
<aside class="sidebar bg-light">
    <div class="tab-content h-100" role="tablist">
        {% include "sidebar-conflict-info.html" %}
        {% include "sidebar-create-chat.html" %}
        {% include "sidebar-contacts.html" %}
        {% include "sidebar-chats.html" %}
        {% include "sidebar-settings.html" %}
    </div>
</aside>
<!-- Sidebar -->

app/templates/signup-code.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <!-- Head -->
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, maximum-scale=1, shrink-to-fit=no, viewport-fit=cover">
        <meta name="color-scheme" content="light dark">

        <title>Mr Fusion</title>

        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static "assets/img/favicon/favicon.ico" %}" type="image/x-icon">

        <!-- Font -->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700" rel="stylesheet">

        <!-- Template CSS -->
        <link class="css-lt" rel="stylesheet" href="{% static "assets/css/template.bundle.css" %}" media="(prefers-color-scheme: light)">

    </head>

    <body class="bg-light">

        <div class="container">
            
            <div class="row align-items-center justify-content-center min-vh-100 gx-0">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                {% endif %}

                <div class="col-12 col-md-5 col-lg-4">
                    {% if form.errors %}
                        <div class="alert alert-danger">
                            {{ form.errors }}
                        </div>
                    {% endif %}
                    <form action="signup" method="post">
                        {% csrf_token %}
                        <div class="card card-shadow border-0">
                            <div class="card-body">
                                <div class="row g-6">
                                    <div class="col-12">
                                        <div class="text-center">
                                            <h3 class="fw-bold mb-2">Sign Up</h3>
                                            <p>Please sign up to continue</p>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating">
                                            {{ form.username }}
                                            <label for="id_first_name">Username</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating">
                                            {{ form.first_name }}
                                            <label for="id_first_name">First Name</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating">
                                            {{ form.last_name }}
                                            <label for="id_last_name">Last Name</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating">
                                            {{ form.email }}
                                            <label for="{{ form.email.label }}">Email</label>
                                        </div>
                                    </div>

                                    <div class="col-12">
                                        <div class="form-floating">
                                            {{ form.password }}
                                            <label for="id_password">Password</label>
                                        </div>
                                    </div>

                                    <div class="col-12">
                                        <div class="form-floating">
                                            {{ form.code }}
                                            <label for="id_code">Code</label>
                                        </div>
                                    </div>

                                    <div class="col-12">
                                        <button class="btn btn-block btn-lg btn-primary w-100" type="submit">Create Account</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
            </div> <!-- / .row -->
        </div>

        <!-- Scripts -->
        <script src="{% static "assets/js/vendor.js" %}"></script>
        <script src="{% static "assets/js/template.js" %}"></script>
    </body>
</html>

app/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <!-- Head -->
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, maximum-scale=1, shrink-to-fit=no, viewport-fit=cover">
        <meta name="color-scheme" content="light dark">

        <title>Mr Fusion</title>

        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static "assets/img/favicon/favicon.ico" %}" type="image/x-icon">

        <!-- Font -->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700" rel="stylesheet">

        <!-- Template CSS -->
        <link class="css-lt" rel="stylesheet" href="{% static "assets/css/template.bundle.css" %}" media="(prefers-color-scheme: light)">

    </head>

    <body class="bg-light">

        <div class="container">
            <div class="row align-items-center justify-content-center min-vh-100 gx-0">

                <div class="col-12 col-md-5 col-lg-4">
                    {% if form.errors %}
                        <div class="alert alert-danger">
                            {{ form.errors }}
                        </div>
                    {% endif %}
                    <form action="signup" method="post">
                        {% csrf_token %}
                        <div class="card card-shadow border-0">
                            <div class="card-body">
                                <div class="row g-6">
                                    <div class="col-12">
                                        <div class="text-center">
                                            <h3 class="fw-bold mb-2">Sign Up</h3>
                                            <p>Please sign up to continue</p>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating">
                                            {{ form.username }}
                                            <label for="id_first_name">Username</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating">
                                            {{ form.first_name }}
                                            <label for="id_first_name">First Name</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating">
                                            {{ form.last_name }}
                                            <label for="id_last_name">Last Name</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating">
                                            {{ form.email }}
                                            <label for="{{ form.email.label }}">Email</label>
                                        </div>
                                    </div>

                                    <div class="col-12">
                                        <div class="form-floating">
                                            {{ form.password }}
                                            <label for="id_password">Password</label>
                                        </div>
                                    </div>

                                    <div class="col-12">
                                        {{ form.token }}
                                        <button class="btn btn-block btn-lg btn-primary w-100" type="submit">Create Account</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
            </div> <!-- / .row -->
        </div>

        <!-- Scripts -->
        <script src="{% static "assets/js/vendor.js" %}"></script>
        <script src="{% static "assets/js/template.js" %}"></script>
    </body>
</html>